name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        deno_version:
          - lts
          - latest
        os:
          - ubuntu-latest
          - macos-latest # macos-14
          - macos-15
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno_version }}

      - name: Verify formatting
        if: matrix.os == 'ubuntu-latest'
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        if: matrix.deno_version == 'latest'
        run: deno task test

      # Lint plugins are not supported by Deno 2.1
      - name: Run tests
        if: matrix.deno_version == 2.1
        run: deno task test --ignore=tests/lint.test.ts

      - name: Test upgrade
        run: deno run -A cli.ts upgrade
